server:
  port: 0
spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/internship
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
upload:
  path: /D:/icon