server:
  port: 8081
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: habit
          uri: lb://habit
          predicates:
            - Path=/habit
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka