server:
  port: 0
spring:
  application:
    name: habit
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
